version: "3.9"

services:
  deno-app:
    build:
      context: .
      dockerfile: docker/DockerFile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: run --allow-net --allow-read main.ts

